name: Damage Calculation Test

on:
  push:
   branches: [ master ]
   
jobs:
  build:
  
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js v10.14.2
     uses: action/setup-node@v1
     with:
       node-version: '10.14.2'
       
   - run: yarn install
   - run: yarn test
